
<P>Lasted update time: <?php print $lastUpdate; ?></p>

<p>This system was set to pick up on school related edits (amenity=school tag) in OpenStreetMap each minute but with a delay of several minutes, however there may also be outages causing much longer delays. If you've done some edits which you're expecting to see, wait a little while (or go do a little more!) before refreshing this page </p>

<P>By Harry Wood. <a href="./edits.csv">Data live updated for this display available in csv</a> or <a href="./edits.db">as an sqlite3 db file</a>.

<p><a href="https://github.com/harry-wood/diffreader">Source code on github</a>. Pull requests welcome!</p>
</body>
</html>
