
<P>Lasted update time: <?php print $lastUpdate; ?></p>

<p>This system was set to pick up on school related edits (amenity=school tag) in OpenStreetMap each minute but with a delay of several minutes, however there may also be outages causing much longer delays. If you've done some edits which you're expecting to see, wait a little while (or go do a little more!) before refreshing this page </p>

<P>By Harry Wood. <a href="./edits.csv">Data live updated for this display available in csv</a> or <a href="./edits.db">as an sqlite3 db file</a>.

<!-- <a href="http://svn.openstreetmap.org/applications/viewer/diffreader/baseball">php source code for the display</a> (very simple so far. <a href="http://harrywood.co.uk/contact-harry.php">Patches welcome</a>) <a href="../diffreader.rb">ruby script for finding matching edits in the minutely diffs</a> 
-->

</body>
</html>
